// <auto-generated />
namespace Training_FPT0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Upccc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Upccc));
        
        string IMigrationMetadata.Id
        {
            get { return "202010311028385_Upccc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
